version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        # image: php:fpm
        image: nanoninja/php-fpm
        tty: true
        volumes:
            - ./code:/code
        networks:
            - code-network

    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
          - "3306:3306"
        environment:
          MYSQL_DATABASE: giphyapp
          MYSQL_USER: laravelapp
          MYSQL_ROOT_PASSWORD: levaral
        command: --init-file /data/application/init.sql
        volumes:
          - ./init.sql:/data/application/init.sql
          - ./dbdata:/var/lib/mysql/
        networks:
          - code-network

networks:
    code-network:
        driver: bridge
